In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("iris.csv")

In [4]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
features = data.iloc[:,:-1].values
label = data.iloc[:,[-1]].values

In [20]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()


In [21]:
# Cross Validation for Accuracy score
from sklearn.model_selection import cross_val_score
cross_val_score(model,
               features,
               label,
               cv = 10)

C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWa

array([0.93333333, 0.86666667, 1.        , 1.        , 1.        ,
       1.        , 0.93333333, 0.93333333, 0.8       , 0.66666667])

In [25]:
# Fold Validation Technique
# K-fold cross validation technique
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

from sklearn.model_selection import KFold
kfold = KFold(n_splits=10,
             shuffle=True,
             random_state=1)
i = 0
for train,test in kfold.split(features):
    i = i + 1
    X_train,X_test = features[train],features[test]
    y_train,y_test= label[train],label[test]
    model.fit(X_train,y_train)
    print('Training Score is {} and Testing score is {} for Sample Split {}'
          .format(model.score(X_train,y_train),model.score(X_test,y_test),i))

C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Training Score is 0.9333333333333333 and Testing score is 0.8 for Sample Split 1
Training Score is 0.9407407407407408 and Testing score is 0.8 for Sample Split 2
Training Score is 0.9407407407407408 and Testing score is 1.0 for Sample Split 3
Training Score is 0.9407407407407408 and Testing score is 0.8666666666666667 for Sample Split 4
Training Score is 0.9407407407407408 and Testing score is 1.0 for Sample Split 5
Training Score is 0.9407407407407408 and Testing score is 0.8666666666666667 for Sample Split 6
Training Score is 0.9259259259259259 and Testing score is 0.9333333333333333 for Sample Split 7
Training Score is 0.9481481481481482 and Testing score is 1.0 for Sample Split 8
Training Score is 0.9259259259259259 and Testing score is 1.0 for Sample Split 9
Training Score is 0.9481481481481482 and Testing score is 0.9333333333333333 for Sample Split 10


C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWa

In [35]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits = 10,
             shuffle = True,
             random_state = 1)
i = 0
for train,test in kfold.split(features):
    i=i+1
    if i == 1 :
        X_train_final,X_test_final,y_train_final,y_test_final = features[train],features[test],label[train],label[test]

In [36]:
from sklearn.linear_model import LogisticRegression
finalModel = LogisticRegression()
finalModel.fit(X_train_final,y_train_final)

C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [37]:
finalModel.score(X_train_final,y_train_final)

0.9333333333333333

In [38]:
finalModel.score(X_test_final,y_test_final)

0.8

In [39]:
# SSS
from sklearn.model_selection import StratifiedShuffleSplit
SSS = StratifiedShuffleSplit(n_splits = 10,
                            test_size = 0.3,
                            random_state = 1)
i = 0
for train,test in SSS.split(features,label):
    i = i+1
    X_train,X_test = features[train],features[test]
    y_train,y_test = label[train],label[test]
    model.fit(X_train,y_train)
    print('Training Score is {} and Testing score is {} for sample split {}'.format(model.score(X_train,y_train),model.score(X_test,y_test),i))

Training Score is 0.9523809523809523 and Testing score is 0.9111111111111111 for sample split 1
Training Score is 0.9142857142857143 and Testing score is 0.9777777777777777 for sample split 2
Training Score is 0.9142857142857143 and Testing score is 0.9555555555555556 for sample split 3
Training Score is 0.9333333333333333 and Testing score is 0.9777777777777777 for sample split 4
Training Score is 0.9333333333333333 and Testing score is 0.8888888888888888 for sample split 5
Training Score is 0.9238095238095239 and Testing score is 0.9111111111111111 for sample split 6
Training Score is 0.9238095238095239 and Testing score is 0.9333333333333333 for sample split 7
Training Score is 0.9238095238095239 and Testing score is 0.9333333333333333 for sample split 8
Training Score is 0.9333333333333333 and Testing score is 0.9333333333333333 for sample split 9
Training Score is 0.9333333333333333 and Testing score is 0.9777777777777777 for sample split 10


C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWa

In [40]:
from sklearn.tree import DecisionTreeClassifier
algo = DecisionTreeClassifier()

In [41]:
from sklearn.ensemble import RandomForestClassifier
algo2 = RandomForestClassifier()

In [42]:
from sklearn.feature_selection import RFE
selectfeatures = RFE(estimator = algo2,
                    step = 1)
selectfeatures.fit(features,label)
print(selectfeatures.support_)
print(data.columns[1:5])
print(selectfeatures.ranking_)

[ True False False  True False]
Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')
[1 3 4 1 2]


C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\CZL\Anaconda3\lib\site-packages\sklearn\e

In [44]:
# RFE SSS model
finalfeatures = features[:,2:4]
print(finalfeatures)

[[3.5 1.4]
 [3.  1.4]
 [3.2 1.3]
 [3.1 1.5]
 [3.6 1.4]
 [3.9 1.7]
 [3.4 1.4]
 [3.4 1.5]
 [2.9 1.4]
 [3.1 1.5]
 [3.7 1.5]
 [3.4 1.6]
 [3.  1.4]
 [3.  1.1]
 [4.  1.2]
 [4.4 1.5]
 [3.9 1.3]
 [3.5 1.4]
 [3.8 1.7]
 [3.8 1.5]
 [3.4 1.7]
 [3.7 1.5]
 [3.6 1. ]
 [3.3 1.7]
 [3.4 1.9]
 [3.  1.6]
 [3.4 1.6]
 [3.5 1.5]
 [3.4 1.4]
 [3.2 1.6]
 [3.1 1.6]
 [3.4 1.5]
 [4.1 1.5]
 [4.2 1.4]
 [3.1 1.5]
 [3.2 1.2]
 [3.5 1.3]
 [3.1 1.5]
 [3.  1.3]
 [3.4 1.5]
 [3.5 1.3]
 [2.3 1.3]
 [3.2 1.3]
 [3.5 1.6]
 [3.8 1.9]
 [3.  1.4]
 [3.8 1.6]
 [3.2 1.4]
 [3.7 1.5]
 [3.3 1.4]
 [3.2 4.7]
 [3.2 4.5]
 [3.1 4.9]
 [2.3 4. ]
 [2.8 4.6]
 [2.8 4.5]
 [3.3 4.7]
 [2.4 3.3]
 [2.9 4.6]
 [2.7 3.9]
 [2.  3.5]
 [3.  4.2]
 [2.2 4. ]
 [2.9 4.7]
 [2.9 3.6]
 [3.1 4.4]
 [3.  4.5]
 [2.7 4.1]
 [2.2 4.5]
 [2.5 3.9]
 [3.2 4.8]
 [2.8 4. ]
 [2.5 4.9]
 [2.8 4.7]
 [2.9 4.3]
 [3.  4.4]
 [2.8 4.8]
 [3.  5. ]
 [2.9 4.5]
 [2.6 3.5]
 [2.4 3.8]
 [2.4 3.7]
 [2.7 3.9]
 [2.7 5.1]
 [3.  4.5]
 [3.4 4.5]
 [3.1 4.7]
 [2.3 4.4]
 [3.  4.1]
 [2.5 4. ]
 [2.6 4.4]

In [49]:
# print finalfeatures
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(finalfeatures,
                                                label,
                                                test_size = 0.2,
                                                random_state = 10)
algo.fit(X_train,y_train)
print(algo.score(X_train,y_train))
print(algo.score(X_test,y_test))

0.9916666666666667
0.9


In [50]:
# Example for feature Importance
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(finalfeatures,
                                                label,
                                                test_size = 0.2,
                                                random_state = 10)
algo = DecisionTreeClassifier()
algo.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')