In [1]:
import numpy as np

In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/CZL/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/CZL/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/CZL/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/C

In [4]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
python -c " import numpy as np; np.info(np.add) "

SyntaxError: invalid syntax (<ipython-input-6-be9b493898b2>, line 1)

In [7]:
Z = np.zeros(10)
Z[4] = 1
print (Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [13]:
Z = np.arange(0,9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
nz = np.nonzero([1,5,0,3,0,8,3,0])
print(nz)

(array([0, 1, 3, 5, 6], dtype=int64),)


In [17]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.04577514 0.6986644  0.30982358]
  [0.73427617 0.50002055 0.23911149]
  [0.22104843 0.13352373 0.48348886]]

 [[0.12688151 0.18125357 0.39792805]
  [0.37975747 0.85268044 0.10806671]
  [0.38097943 0.92417934 0.67032849]]

 [[0.79363008 0.46370087 0.4365522 ]
  [0.52918521 0.86534899 0.91736662]
  [0.77722768 0.74890108 0.91322543]]]


In [24]:
Z = np.random.random((10,10))
Zmin , Zmax = Z.min(),Z.max()
print(Z)
print(Zmin , Zmax)

[[0.74606889 0.29321227 0.50379511 0.00461278 0.93949506 0.68559782
  0.25327317 0.31967842 0.85145515 0.98186385]
 [0.56181229 0.78015005 0.99871047 0.51957793 0.4413861  0.25509126
  0.13106127 0.96902257 0.08870403 0.64720189]
 [0.53143222 0.78045663 0.04968488 0.35284119 0.00782063 0.69144655
  0.2545102  0.51558228 0.78963228 0.09405903]
 [0.79517212 0.87046023 0.90222632 0.97491373 0.66343641 0.95403518
  0.75934921 0.56363919 0.13059536 0.87174521]
 [0.85482451 0.97117686 0.26983526 0.81643004 0.0587945  0.42466499
  0.10433737 0.23895191 0.48964928 0.5423697 ]
 [0.15142422 0.84763508 0.52730638 0.58936861 0.62458716 0.19198661
  0.67940891 0.27130644 0.0575262  0.66532753]
 [0.45092047 0.71318921 0.7517345  0.09693382 0.04562697 0.70981722
  0.27644054 0.44282241 0.94582099 0.64755823]
 [0.58989872 0.73378727 0.4175524  0.16572297 0.09145377 0.59401219
  0.60526795 0.35869911 0.78065866 0.70932517]
 [0.12006382 0.12313314 0.0820922  0.7733454  0.88650587 0.40489358
  0.52745086

In [27]:
Z = np.random.random(30)
MZ= Z.mean()
print(MZ)

0.5947512340386272


In [29]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [30]:
0*np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3*0.1

False

In [31]:
0.3 == 3*0.1

False

In [32]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [34]:
Z = np.zeros((8,8), dtype = int)
Z[1::2,::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


TypeError: 'int' object is not callable