In [1]:
import numpy as np

In [3]:
onedarray = np.array([1,2,3,4,5,6])
print(onedarray)

[1 2 3 4 5 6]


In [4]:
onedarray.shape

(6,)

In [7]:
onedarray2=np.array([2,5,6,3,5,2])
print(onedarray2)

[2 5 6 3 5 2]


In [8]:
result = onedarray+onedarray2
result

array([ 3,  7,  9,  7, 10,  8])

In [9]:
# two Dimensional array
twodarray=np.array([[1,2,3],[4,5,6]])
twodarray

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
twodarray2= np.array([[2,3,4],[4,5,6]])
result = twodarray+twodarray2
print (result)

[[ 3  5  7]
 [ 8 10 12]]


In [11]:
import pandas as pd

In [20]:
data = pd.read_csv(r"E:\Data Scientist\Machine Learning\Prashant sir\Notes\Day3\employee.csv", header = None , names = ("EID","Ename","Esal"))

In [21]:
data.head()

EID     Ename  Esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    4  Utkarsha  9878
4    5      Ajit  9999

In [22]:
data["EID"]

0    1
1    2
2    3
3    4
4    5
Name: EID, dtype: int64

In [23]:
data.iloc[:,:]

EID     Ename  Esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    4  Utkarsha  9878
4    5      Ajit  9999

In [24]:
data.loc[:,['EID']]

EID
0    1
1    2
2    3
3    4
4    5

In [27]:
# Adding new Column
Yearly_salary=data.Esal*12
data['Yearly_salary'] = Yearly_salary
data

EID     Ename  Esal  Yearly_salary
0    1  Prashant  1000          12000
1    2      Amar  2000          24000
2    3    Chitra  2000          24000
3    4  Utkarsha  9878         118536
4    5      Ajit  9999         119988

In [30]:
data.to_csv(r'E:\Data Scientist\Machine Learning\Prashant sir\Notes\Day3\FinalDataSet.csv',index = False)

In [33]:
# Dataframe
Data_Frame = pd.DataFrame(np.array(range(1,10)).reshape(3,3))
Data_Frame

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [37]:
# convert dataframe into array
import numpy as np
Data_Frame.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])